# Generated by Django 5.0.7 on 2024-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('num_people', models.IntegerField()),
                ('round_trip', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pickup_start', models.CharField(max_length=100)),
                ('destination_start', models.CharField(max_length=100)),
                ('pickup_end', models.CharField(max_length=100)),
                ('destination_end', models.CharField(max_length=100)),
            ],
        ),
    ]
