# Generated by Django 5.0.7 on 2024-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='newss_later',
            field=models.BooleanField(default=False),
        ),
    ]
