# Generated by Django 5.0.7 on 2024-08-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_rename_mail_contact_email_contact_newss_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportacion',
            name='contact_phone',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='passenger_names',
            field=models.TextField(blank=True),
        ),
    ]
