# Generated by Django 5.0.7 on 2024-09-04 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0005_transportacion_contact_phone_transportacion_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='num_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de personas'),
        ),
    ]
