# Generated by Django 5.0.7 on 2024-09-05 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_alter_transportacion_num_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportacion',
            name='destination_end',
        ),
        migrations.RemoveField(
            model_name='transportacion',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='transportacion',
            name='passenger_names',
        ),
        migrations.RemoveField(
            model_name='transportacion',
            name='pickup_end',
        ),
        migrations.AddField(
            model_name='transportacion',
            name='num_adults',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de adultos'),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='num_children',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Numero  de Menores'),
        ),
    ]
