# Generated by Django 5.0.7 on 2024-09-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_remove_transportacion_destination_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='contact_phone',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
