# Generated by Django 5.0.7 on 2024-09-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0008_alter_transportacion_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportacion',
            name='lada',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
