# Generated by Django 5.0.7 on 2024-09-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0009_transportacion_lada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='lada',
            field=models.CharField(max_length=3),
        ),
    ]
