# Generated by Django 5.0.7 on 2024-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0010_alter_transportacion_lada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='contact_phone',
            field=models.CharField(max_length=13),
        ),
    ]
