# Generated by Django 5.0.7 on 2024-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0011_alter_transportacion_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='destination_start',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
