# Generated by Django 5.0.7 on 2024-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0012_alter_transportacion_destination_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='destination_start',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='pickup_start',
            field=models.CharField(max_length=255),
        ),
    ]
