# Generated by Django 5.0.7 on 2024-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0013_alter_transportacion_destination_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='destination_start',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='round_trip',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
