# Generated by Django 5.0.7 on 2024-09-08 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0014_alter_transportacion_destination_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='num_children',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Numero  de Menores'),
        ),
    ]
