# Generated by Django 5.0.7 on 2024-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0016_alter_transportacion_round_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='end_date',
            field=models.DateTimeField(blank=True, default='-', null=True),
        ),
    ]
