# Generated by Django 5.0.7 on 2024-09-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0017_alter_transportacion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='round_trip',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
