# Generated by Django 5.0.7 on 2024-09-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0020_alter_transportacion_round_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='round_trip',
            field=models.BooleanField(blank=True, default='-', null=True),
        ),
    ]
