# Generated by Django 5.0.7 on 2024-09-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0023_alter_transportacion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='end_date',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
    ]
