# Generated by Django 5.0.7 on 2024-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0024_alter_transportacion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='contact_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
