# Generated by Django 5.0.7 on 2024-09-09 23:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0025_alter_transportacion_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportacion',
            name='lada',
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Teléfono de contacto'),
        ),
    ]
