# Generated by Django 5.0.7 on 2024-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0026_remove_transportacion_lada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportacion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de regreso'),
        ),
        migrations.AlterField(
            model_name='transportacion',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha y hora de inicio'),
        ),
    ]
