# Generated by Django 5.0.7 on 2024-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0027_alter_transportacion_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportacion',
            name='airline_arrival',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='airline_departure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='flight_number_arrival',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='flight_number_departure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='terminal_arrival',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportacion',
            name='terminal_departure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
