# Generated by Django 5.0.7 on 2024-10-29 00:03

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0029_vehicletype_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holder_name', models.CharField(max_length=200)),
                ('total_adults', models.PositiveIntegerField()),
                ('total_children', models.PositiveIntegerField()),
                ('additional_notes', models.TextField()),
                ('service_type', models.CharField(choices=[('TRANSPORT', 'Transporte'), ('TOUR', 'Tour'), ('LODGING', 'Hospedaje')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Teléfono de contacto')),
                ('adult_ages', models.JSONField(default=list)),
                ('children_ages', models.JSONField(default=list)),
                ('transport_type', models.CharField(blank=True, choices=[('ROUND', 'Redondo'), ('SINGLE', 'Sencillo')], max_length=10, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('custom_tour_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tour_datetime', models.DateTimeField(blank=True, null=True)),
                ('requires_pickup', models.BooleanField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('room_count', models.PositiveIntegerField(blank=True, null=True)),
                ('lodging_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_app.tour'),
        ),
    ]
