# Generated by Django 5.1.3 on 2024-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0030_servicerequest_tour_delete_tours_servicerequest_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='additional_notes',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requires_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='transport_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
