# Generated by Django 5.1.3 on 2024-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0031_remove_servicerequest_additional_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='adult_ages',
            new_name='child_ages',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='children_ages',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('ROUND', 'Redondo'), ('SINGLE', 'Sencillo')], max_length=10, null=True),
        ),
    ]
