# Generated by Django 5.1.3 on 2024-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0032_rename_adult_ages_servicerequest_child_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='child_ages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
