# Generated by Django 5.1.3 on 2024-11-25 17:12

import collection_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0033_alter_servicerequest_child_ages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='tour',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_in_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_out_date',
            field=models.DateTimeField(blank=True, default=collection_app.models.default_check_out_date, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tour_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
