# Generated by Django 5.1.3 on 2024-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0034_remove_servicerequest_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='tours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
