# Generated by Django 5.1.3 on 2024-11-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0035_servicerequest_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='tours',
        ),
    ]
