# Generated by Django 5.1.3 on 2024-11-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0036_remove_servicerequest_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='collection_app.tour'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('TRANSPORT', 'Transporte'), ('TOUR', 'Tour'), ('LODGING', 'Hospedaje')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tour_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
