# Generated by Django 5.1.3 on 2024-11-25 21:15

import collection_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0037_servicerequest_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='tour',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_in_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='check_out_date',
            field=models.DateTimeField(blank=True, default=collection_app.models.default_check_out_date, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('TRANSPORT', 'Transporte'), ('TOUR', 'Tour'), ('LODGING', 'Hospedaje')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_adults',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tour_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
