# Generated by Django 5.1.3 on 2024-11-25 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0038_remove_servicerequest_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_app.tour'),
        ),
    ]
